name = "lean-proofs"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["All"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "f897ebcf72cd16f89ab4577d0c826cd14afaafc7"

[[lean_lib]]
name = "All"

[[lean_lib]]
name = "ErdosProblems"

[[lean_lib]]
name = "HundredTheorems"

[[lean_lib]]
name = "MathOverflow"
